### ISSUE TITLE
Dataset and functions

### ISSUE THREAD

**Issue by stylebased** [MADSOLSEN/SleepStagePrediction#1]
Hi,
I am really interested in your paper. However I can not find the link to download the dataset you are using. There are some functions missing either. Can you fix these two problems?
Thanks

**Comment by MADSOLSEN** [comment]
The authors do not have permission to share the data used in this study at this point in time. However, the pretrained model is available. Use minimal_example to get started. Also, the functions should be up to date now. Let me know if you run into any problems.
