### ISSUE TITLE
superlet and ggir_ext not in signal_processing

### ISSUE THREAD

**Issue by MarianaAbreu** [MADSOLSEN/SleepStagePrediction#2]
Hi,

I was trying to run your pretrained model, however some scripts are missing, namely the scripts superlet and ggir_ext from signal_processing. 
Superlet seems to be necessary when importing the model ResUNet from models, which is needed to "test the pretrained model" according to your train and evaluate notebook.

Thank you in advance,
M

**Comment by MADSOLSEN** [comment]
Hi Mariana, 

Thanks for raising my attention to this. The superlet library is actually not used, so I'll make to update the functions to work without it in the coming week. 

best, 
Mads

**Comment by MADSOLSEN** [comment]
I've updated the repository to include ggir_ext and superlet lib. Let me know if it works for you now, 
Best, Mads
